2023-05-05 03:40:31 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 03:40:31 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 77
2023-05-05 03:46:14 ERROR django.request Internal Server Error: /api/v1/doc/schema/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/views.py", line 83, in get
    return self._get_schema_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/views.py", line 91, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/utils.py", line 410, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 83, in get_operation
    request_body = self._get_request_body()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1277, in _get_request_body
    schema, request_body_required = self._get_request_for_media_type(request_serializer, direction)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1308, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1575, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 907, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 999, in _map_basic_serializer
    for field in serializer.fields.values():
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'email' was declared on serializer RecruiterProfileSerializer, but has not been included in the 'fields' option.
2023-05-05 03:46:14 ERROR django.server "GET /api/v1/doc/schema/ HTTP/1.1" 500 182500
2023-05-05 03:46:14 ERROR django.request Internal Server Error: /api/v1/doc/schema/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/views.py", line 83, in get
    return self._get_schema_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/views.py", line 91, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/utils.py", line 410, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 83, in get_operation
    request_body = self._get_request_body()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1277, in _get_request_body
    schema, request_body_required = self._get_request_for_media_type(request_serializer, direction)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1308, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1575, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 907, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 999, in _map_basic_serializer
    for field in serializer.fields.values():
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'email' was declared on serializer RecruiterProfileSerializer, but has not been included in the 'fields' option.
2023-05-05 03:46:14 ERROR django.server "GET /api/v1/doc/schema/ HTTP/1.1" 500 182500
2023-05-05 04:01:35 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 125, in update
    print(444444444444444444444444444, **validated_data)
TypeError: 'email' is an invalid keyword argument for print()
2023-05-05 04:01:35 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 129572
2023-05-05 04:03:17 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 125, in update
    print(4444444444444444, self.context["request"].user.user)
AttributeError: 'User' object has no attribute 'user'
2023-05-05 04:03:17 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 129626
2023-05-05 04:05:22 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 129, in update
    user.email = user_data.get("email", user.email)
AttributeError: 'User' object has no attribute 'get'
2023-05-05 04:05:22 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 129363
2023-05-05 04:07:09 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 129, in update
    user.email = user_data.get("email", user.email)
AttributeError: 'User' object has no attribute 'get'
2023-05-05 04:07:09 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 129370
2023-05-05 04:08:03 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 127, in update
    user = instance.email
AttributeError: 'Recruiter' object has no attribute 'email'
2023-05-05 04:08:03 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 129254
2023-05-05 04:08:25 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 129, in update
    user.save()
AttributeError: 'str' object has no attribute 'save'
2023-05-05 04:08:25 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 129139
2023-05-05 04:08:28 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 129, in update
    user.save()
AttributeError: 'str' object has no attribute 'save'
2023-05-05 04:08:28 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 129139
2023-05-05 04:09:40 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 129, in update
    User.save()
TypeError: AbstractBaseUser.save() missing 1 required positional argument: 'self'
2023-05-05 04:09:40 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 129226
2023-05-05 04:09:46 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 129, in update
    User.save()
TypeError: AbstractBaseUser.save() missing 1 required positional argument: 'self'
2023-05-05 04:09:46 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 129226
2023-05-05 04:09:54 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 129, in update
    User.save(self)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/contrib/auth/base_user.py", line 76, in save
    super().save(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
2023-05-05 04:09:54 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 133976
2023-05-05 04:16:03 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 127, in update
    user.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/contrib/auth/base_user.py", line 76, in save
    super().save(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
2023-05-05 04:16:03 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 217998
2023-05-05 04:16:44 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:16:44 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:17:36 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:17:36 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:17:47 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 127, in update
    user.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/contrib/auth/base_user.py", line 76, in save
    super().save(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
2023-05-05 04:17:47 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 217798
2023-05-05 04:18:37 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:18:37 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:24:12 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:24:12 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:24:59 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:24:59 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:25:01 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:25:01 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:28:59 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:28:59 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:29:21 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2055, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'User'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 98, in is_valid
    queryset = Recruiter.objects.exclude(id=self.instance.user)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1444, in exclude
    return self._filter_or_exclude(True, args, kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1459, in _filter_or_exclude_inplace
    self._query.add_q(~Q(*args, **kwargs))
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1444, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1271, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2057, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <User: recruiter@example.com>.
2023-05-05 04:29:21 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 182504
2023-05-05 04:29:41 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:29:41 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:29:41 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:29:41 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:36:07 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:36:07 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:36:26 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:36:26 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:38:43 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:38:43 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:44:52 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 131, in update
    return super().update(user=user, **validated_data)
TypeError: ModelSerializer.update() got an unexpected keyword argument 'user'
2023-05-05 04:44:52 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 128793
2023-05-05 04:45:22 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 131, in update
    return super().update(**validated_data)
TypeError: ModelSerializer.update() missing 2 required positional arguments: 'instance' and 'validated_data'
2023-05-05 04:45:22 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 129017
2023-05-05 04:45:25 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 131, in update
    return super().update(**validated_data)
TypeError: ModelSerializer.update() missing 2 required positional arguments: 'instance' and 'validated_data'
2023-05-05 04:45:25 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 129017
2023-05-05 04:45:47 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 131, in update
    return super().update(instance, **validated_data)
TypeError: ModelSerializer.update() missing 1 required positional argument: 'validated_data'
2023-05-05 04:45:47 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 128881
2023-05-05 04:46:25 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 131, in update
    return super().update(instance, validated_data, email=email)
TypeError: ModelSerializer.update() got an unexpected keyword argument 'email'
2023-05-05 04:46:25 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 128819
2023-05-05 04:48:16 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:48:16 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:48:18 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:48:18 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:48:40 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:48:40 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:49:10 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:49:10 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:49:48 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:49:48 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 88
2023-05-05 04:53:52 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:53:52 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 24
2023-05-05 04:54:40 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:54:40 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 62
2023-05-05 04:55:10 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:55:10 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 62
2023-05-05 04:55:58 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/recruiter/api/viewsets/add_job.py", line 283, in update
    return super().update(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/suraj/Desktop/python/recruiter/api/serializers/add_job.py", line 136, in update
    user.save()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/contrib/auth/base_user.py", line 76, in save
    super().save(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
2023-05-05 04:55:58 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 217708
2023-05-05 04:56:20 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:56:20 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 62
2023-05-05 04:56:24 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:56:24 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 62
2023-05-05 04:56:25 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:56:25 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 62
2023-05-05 04:56:33 WARNING django.request Bad Request: /api/v1/recruiter/change-profile/18/
2023-05-05 04:56:33 WARNING django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 400 62
2023-05-05 05:21:45 ERROR django.request Internal Server Error: /api/v1/recruiter/change-profile/18/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2023-05-05 05:21:45 ERROR django.server "PATCH /api/v1/recruiter/change-profile/18/ HTTP/1.1" 500 105917
2023-05-05 06:13:15 ERROR django.server "GET /api/v1/doc/schema/ HTTP/1.1" 500 59
2023-05-05 06:13:15 ERROR django.server "GET /api/v1/doc/schema/ HTTP/1.1" 500 59
2023-05-05 06:13:17 ERROR django.server "GET /api/v1/doc/ HTTP/1.1" 500 59
2023-05-05 06:13:18 ERROR django.server "GET /api/v1/doc/ HTTP/1.1" 500 59
2023-05-05 06:46:08 WARNING django.request Not Found: /
2023-05-05 06:46:08 WARNING django.server "GET / HTTP/1.1" 404 2425
2023-05-05 16:21:56 WARNING django.request Not Found: /
2023-05-05 16:21:56 WARNING django.server "GET / HTTP/1.1" 404 2425
2023-05-05 16:21:56 WARNING django.request Not Found: /favicon.ico
2023-05-05 16:21:56 WARNING django.server "GET /favicon.ico HTTP/1.1" 404 2476
2023-05-05 17:14:26 WARNING django.request Not Found: /
2023-05-05 17:14:26 WARNING django.server "GET / HTTP/1.1" 404 2425
2023-05-05 17:49:55 WARNING django.request Not Found: /
2023-05-05 17:49:55 WARNING django.server "GET / HTTP/1.1" 404 2425
2023-05-05 17:50:30 WARNING django.request Unauthorized: /api/v1/recruiter/job-post/
2023-05-05 17:50:30 WARNING django.server "POST /api/v1/recruiter/job-post/ HTTP/1.1" 401 57
2023-05-05 17:50:41 WARNING django.request Bad Request: /api/v1/recruiter/job-post/
2023-05-05 17:50:41 WARNING django.server "POST /api/v1/recruiter/job-post/ HTTP/1.1" 400 39
