2023-05-04 11:07:05 WARNING django.request Bad Request: /api/v1/miscellaneous/info/
2023-05-04 11:07:05 WARNING django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 400 85
2023-05-04 11:18:04 WARNING django.request Not Found: /media/common/1683199065511823.png
2023-05-04 11:18:04 WARNING django.server "GET /media/common/1683199065511823.png HTTP/1.1" 404 2289
2023-05-04 11:21:05 WARNING django.request Bad Request: /api/v1/miscellaneous/info/
2023-05-04 11:21:05 WARNING django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 400 85
2023-05-04 11:23:50 WARNING django.request Bad Request: /api/v1/miscellaneous/info/
2023-05-04 11:23:50 WARNING django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 400 85
2023-05-04 11:35:32 WARNING django.request Unauthorized: /api/v1/miscellaneous/info/
2023-05-04 11:35:32 WARNING django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 401 57
2023-05-04 11:35:42 WARNING django.request Bad Request: /api/v1/miscellaneous/info/
2023-05-04 11:35:42 WARNING django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 400 85
2023-05-04 11:35:54 WARNING django.request Bad Request: /api/v1/miscellaneous/info/
2023-05-04 11:35:54 WARNING django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 400 85
2023-05-04 11:39:08 WARNING django.request Bad Request: /api/v1/miscellaneous/info/
2023-05-04 11:39:08 WARNING django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 400 55
2023-05-04 12:01:04 ERROR django.request Internal Server Error: /api/v1/miscellaneous/info/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/miscellaneous/api/viewsets/informative.py", line 239, in create
    "data": super().create(request, *args, **kwargs).data,
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/home/suraj/Desktop/python/miscellaneous/api/serializers/informative.py", line 27, in is_valid
    print(data.get("content")).get("image")
AttributeError: 'NoneType' object has no attribute 'get'
2023-05-04 12:01:04 ERROR django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 500 108320
2023-05-04 12:04:36 ERROR django.request Internal Server Error: /api/v1/miscellaneous/info/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/miscellaneous/api/viewsets/informative.py", line 239, in create
    "data": super().create(request, *args, **kwargs).data,
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/home/suraj/Desktop/python/miscellaneous/api/serializers/informative.py", line 27, in is_valid
    print(data.get("content")).content("image")
AttributeError: 'NoneType' object has no attribute 'content'
2023-05-04 12:04:36 ERROR django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 500 108352
2023-05-04 12:04:39 ERROR django.request Internal Server Error: /api/v1/miscellaneous/info/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/miscellaneous/api/viewsets/informative.py", line 239, in create
    "data": super().create(request, *args, **kwargs).data,
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/home/suraj/Desktop/python/miscellaneous/api/serializers/informative.py", line 27, in is_valid
    print(data.get("content")).content("image")
AttributeError: 'NoneType' object has no attribute 'content'
2023-05-04 12:04:39 ERROR django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 500 108352
2023-05-04 12:04:54 ERROR django.request Internal Server Error: /api/v1/miscellaneous/info/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/miscellaneous/api/viewsets/informative.py", line 239, in create
    "data": super().create(request, *args, **kwargs).data,
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/home/suraj/Desktop/python/miscellaneous/api/serializers/informative.py", line 27, in is_valid
    print(data.get("content")).content("image")
AttributeError: 'NoneType' object has no attribute 'content'
2023-05-04 12:04:54 ERROR django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 500 108352
2023-05-04 12:05:24 ERROR django.request Internal Server Error: /api/v1/miscellaneous/info/
Traceback (most recent call last):
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/Desktop/python/miscellaneous/api/viewsets/informative.py", line 239, in create
    "data": super().create(request, *args, **kwargs).data,
  File "/home/suraj/Desktop/python/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/home/suraj/Desktop/python/miscellaneous/api/serializers/informative.py", line 27, in is_valid
    print(data.get("content").content("image"))
AttributeError: 'dict' object has no attribute 'content'
2023-05-04 12:05:24 ERROR django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 500 108328
2023-05-04 12:08:31 WARNING django.request Bad Request: /api/v1/miscellaneous/info/
2023-05-04 12:08:31 WARNING django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 400 37
2023-05-04 12:11:48 WARNING django.request Bad Request: /api/v1/miscellaneous/info/
2023-05-04 12:11:48 WARNING django.server "POST /api/v1/miscellaneous/info/ HTTP/1.1" 400 37
